Module6 task1
htmlacademy-react/1136803-six-cities-5 pull request #10
Opened 2020-11-10 12:31 UTC by ildarjans

Ниже привожу задание к этому модулю.
У меня уже сейчас нет нигде стейта в компонентах.

### Задание
>Пересмотрите существующие компоненты. Избавьтесь от внутреннего стейта в компонентах — перенесите стейт в компоненты высшего порядка (HOC).

>Запустите ваше приложение и посмотрите на него со стороны инструментов React DevTools и Redux DevTools. Посмотрите как выполняется перерисовка компонентов (с включенным флагом highlight), посмотрите как работает TimeLine-отладка. Найдите узкие места и попытайтесь устранить их с помощью

>Пересмотрите компонент «Список карточек с предложениями» и похожие. У таких компонентов есть одно большое сходство: в каждом из них требуется выделять активный элемент списка. Создайте в директории /src/hocs новый HOC withActiveItem (название может быть любым). Задача компонента: применить общее поведение (выделение элемента) для похожих компонентов-списков. Оберните компоненты с помощью созданного HOC.

Реализацию описанную в последнем компоненте я сделал через глобальный стейт. Переписать это на Хоки будет нелепо да и зачем ? 

В этом задании избавился от классового компонента Map. Методы этого класса вынес HOC. 
Что в рамках этого задания еще нужно сделать - не понимаю.

2020-11-12 02:13 UTC, sahaviev commented on src/hocs/with-map-leaflet.jsx
> +export const withMapLeaflet = (Component) => {
withLeafletMap - правильнее звучит 🙂☺️

2020-11-12 02:14 UTC, sahaviev commented on src/components/map/map.jsx
> +const MapContainer = (props, ref) => {
MapContainer -> **Map**

2020-11-12 02:16 UTC, sahaviev commented on src/components/tabs/tabs.jsx
> +const TabsComponent = ({activeCity, onCityChange}) => {
TabsComponent -> слишком общее название, но он знает много чего про city...
Т.е. переиспользовать его ты не сможешь скорее всего. Поэтому предлагаю его переименовать в CitiesTabs.

2020-11-12 02:19 UTC, sahaviev commented
Здесь предлагается хранить в HOCах(withActiveItem) состояние активных оферов. Что может быть причиной разворачивания попытки защиты при сдачи проекта.
В принципе у тебя он в store редакса хранится. Созвонимся и подумаем нужно или нет переделывать.

2020-11-12 02:20 UTC, sahaviev commented
Если нормально делать этот проект то кажется что особо много чего переделывать здесь не нужно. PR маленький не только у тебя был.

2020-11-12 02:21 UTC, sahaviev requested changes
Мелкие фиксы нужны. В комментариях отписал где

2020-11-14 19:25 UTC, ildarjans commented on src/components/map/map.jsx
> +const MapContainer = (props, ref) => {
У меня тут дальше экспортируется Map подключенный к store.  
Экспортировать короткий Map лучше, чем LeafletMap или WrappedMap.  
Поэтому пока не понимаю как понять твое предложение.

2020-11-15 02:39 UTC, sahaviev commented on src/components/map/map.jsx
> +const MapContainer = (props, ref) => {
В таком случае MapComponent оставить.  Container - это про другое в React.

2020-11-15 02:41 UTC, sahaviev commented on src/components/map/map.jsx
> +// export const Map = connect(mapStateToProps)(withLeafletMap(MapComponent));
Тоже норм.

2020-11-15 02:41 UTC, sahaviev commented on src/components/tabs/tabs.jsx
> +export const Tabs = connect(mapStateToProps, mapDispatchToProps)(LocationsTabs);
LocationsTabs  -> **LocationsTabsComponent**
Tabs -> **LocationsTabs**

2020-11-15 02:42 UTC, sahaviev approved these changes
Пару комментов оставил, но так в целом двигайся дальше.

2020-11-15 02:42 UTC, merged