Module4 task2
htmlacademy-react/1136803-six-cities-5 pull request #8
Opened 2020-11-02 20:25 UTC by ildarjans

2020-11-06 00:50 UTC, sahaviev commented on src/const.js
> +    zoom: 10,
У тебя сейчас zoom везде 10...
Очень странное решение отдавать ответственность за него самому городу. Я бы карте также оставил.

2020-11-06 00:51 UTC, sahaviev commented on src/store/reducer.js
> +  });
Можно обойтись одним foreach

2020-11-06 00:52 UTC, sahaviev commented on src/store/reducer.js
> +  });
Функция использует глобальное состояние - cities. Это плохо в данном случае.

2020-11-06 00:53 UTC, sahaviev commented on src/store/reducer.js
> +const cityOffers = getCityOffers(offers);
можно вызов сделать в initialState самом и избавиться от переменной cityOffers

2020-11-06 00:55 UTC, sahaviev commented on src/store/props-to-state-selectors.js
> +export const getOffers = (state) => {
это **selectCityOffers** скорее, **selectOffers** - это когда выбираешь все офферы.
Селекторы называй со слова **select**

2020-11-06 16:09 UTC, ildarjans commented on src/const.js
> +    zoom: 10,
подсмотрел как будут приходить данные с сервера и сделал так же

2020-11-07 23:33 UTC, sahaviev commented on src/components/place-card/place-card.jsx
> +});
???

2020-11-07 23:33 UTC, sahaviev commented on src/components/property/property.jsx
> +            <Map key={id} propsForMap={propsForMap}/>
key={id} - зло здесь )

2020-11-07 23:39 UTC, sahaviev commented on src/components/cities/cities.jsx
> +            <Map key={activeCity} propsForMap={propsForMap}/>
**key={activeCity}** - удалить

2020-11-07 23:39 UTC, sahaviev requested changes
Обсудили на консультации, нужно много чего доработать )

2020-11-08 21:45 UTC, sahaviev commented on src/components/cities/cities.jsx
> +  mapIcons
Здесь я бы оставил постфикс PropTypes. Кажется, опять ты переделал как не нужно)
Теоретически у тебя mapCenter и mapIcons могут быть использованы как константы в твоем компоненте и тогда могут возникнуть. Придется делать alias. А переменная mapCenterPropTypes у тебя вряд-ли будет где-то еще использоваться в проекте.
Обычно линтеры ругаются на то что в файле используются пусть даже в разных функциях(областях видимости) переменные с одинаковыми названиями.

2020-11-08 21:46 UTC, sahaviev commented on src/components/cities/cities.jsx
> +  mapIcons
Да и собери в одну строчку, там вмещается..

2020-11-08 21:52 UTC, sahaviev approved these changes
Да, получилось прям чисто и красиво.
Прям 🔥🔥🔥
По сравнению с тем что было )
Докопаться всегда можно до чего-то, но в целом с таким уже можно двигаться дальше.

2020-11-08 21:53 UTC, merged