Module5 task2
htmlacademy-react/1136803-six-cities-5 pull request #9
Opened 2020-11-08 22:00 UTC by ildarjans

2020-11-09 21:48 UTC, sahaviev commented on src/store/action.js
> +  CHANGE_SORT_TYPE: `CHANGE_SORT_ORDER`
ActionType и литералы которые справа ты описал принято называть одинаково...

2020-11-09 21:50 UTC, sahaviev commented on src/utils.js
> +export const sortOffersTopRated = (offerA, offerB) => offerB.rating - offerA.rating;
Я бы не стал это выносить в отдельную функцию, т.к. ты скорее всего их больше нигде не переиспользуешь.

2020-11-09 21:59 UTC, sahaviev commented on src/selectors/offers.js
> +);
Ты в селекторе получения офферов инкапсулировал логику фильтрации, решение рабочее, на на мой взгляд, лучше так не смешивать.

2020-11-09 22:03 UTC, sahaviev commented on src/hocs/with-collapse-toggle.jsx
> +    }
Это нужно переписать вот так вот:
```
handleCollapseToggle() {
      this.setState((state) => {
            collapsed: !state.collapsed
      );
}
```
Прочитай про setState и его callback

2020-11-09 22:04 UTC, sahaviev commented on src/hocs/with-collapse-toggle.jsx
> +      const {collapsed} = this.state;
Можно обойтись без деструктуризации, читабельность не пострадает

2020-11-09 22:05 UTC, sahaviev commented on src/hocs/with-collapse-toggle.jsx
> +  class SortPlacesComponent extends React.PureComponent {
У тебя сейчас есть HOC: withCollapseToggle, но внутри него компонент ты назвал SortPlacesComponent, по сути HOCи нужны чтобы ты мог переиспользовать код, а ты своим названием его привязал к проекту.
Я бы назвал **CollapseToggle**

2020-11-09 22:06 UTC, sahaviev commented on src/const.js
> +export const sortTypeTitle = {
**sortTypeTitles**

2020-11-09 22:08 UTC, sahaviev commented on src/components/places-sorting/places-sorting.jsx
> +            }}
eslint-no-bind.
Вытащи в функцию

2020-11-09 22:13 UTC, sahaviev requested changes
Нужны доработки, отписал все в комментариях )

2020-11-09 22:24 UTC, ildarjans commented on src/utils.js
> +export const sortOffersTopRated = (offerA, offerB) => offerB.rating - offerA.rating;
так аккуратней получается

2020-11-09 22:26 UTC, ildarjans commented on src/selectors/offers.js
> +);
в стейт записывать и через редюсер вызывать?

2020-11-09 22:29 UTC, ildarjans commented on src/hocs/with-collapse-toggle.jsx
> +      const {collapsed} = this.state;
eslint ругается если писать this.state.collapsed

2020-11-09 22:40 UTC, ildarjans commented on src/hocs/with-collapse-toggle.jsx
> +      const {collapsed} = this.state;
без деструктуризации eslint пишет Unresolved variable collapsed

2020-11-10 01:41 UTC, sahaviev commented on src/hocs/with-collapse-toggle.jsx
> +      const {collapsed} = this.state;
А если так напишешь: **this.state.collapsed** ?

2020-11-10 01:41 UTC, sahaviev commented on src/store/action.js
> +  CHANGE_ACTIVE_OFFER_ID: `CHANGE_ACTIVE_OFFER`,
Здесь тоже)

2020-11-10 01:42 UTC, sahaviev approved these changes
Двигаемся дальше )
Оставил 2 коммента, глянь, если что потом пофиксим на созвоне

2020-11-10 01:42 UTC, merged